// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkhiifqkvkibdozdaaoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndraGlpZnFrdmtpYmRvemRhYW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzIyNjYsImV4cCI6MjA2MDgwODI2Nn0.KmdoYjZYZe-ssUbih-9VoN25kgIu7FSNKVw3r_bL01A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);